CACHE TABLE GENE_VIRULENCE_STAGING;

DROP TABLE IF EXISTS GENE_VIRULENCE;

CREATE TABLE GENE_VIRULENCE
  USING PARQUET
  AS
  SELECT
    GENE_UID_KEY,
    SHORT_NAME,
    FULL_NAME,
    VIRULENCE_FACTOR,
    LOWER(GENUS_NAME) AS GENUS_NAME,
    SPECIES_NAME,
    STRAIN
    FROM
      GENE_VIRULENCE_STAGING;

CACHE TABLE GENE_VIRULENCE;

SELECT
  COUNT(1) AS NUM_ROWS,
  COUNT(DISTINCT GENE_UID_KEY) AS NUM_DISTINCT_GENES
  FROM
    GENE_VIRULENCE;

SELECT *
  FROM
    GENE_VIRULENCE
    ORDER BY 1
    LIMIT 10;

DROP TABLE GENE_VIRULENCE_STAGING;
