CACHE TABLE GENOME_PROTEIN_STAGING;

CACHE TABLE GENOME_TABLE_STAGING;

CACHE TABLE PROTEIN_DETAILS_STAGING;

DROP TABLE IF EXISTS GENOME_PROTEIN;

CREATE TABLE GENOME_PROTEIN
  USING PARQUET
  AS
  SELECT
    B.ACCESSION_NUMBER,
    B.PROTEIN_UID_KEY,
    B.LOCUS
    FROM
      GENOME_TABLE_STAGING A
      INNER JOIN GENOME_PROTEIN_STAGING B ON
        B.ACCESSION_NUMBER = A.ACCESSION_NUMBER
      INNER JOIN PROTEIN_DETAILS_STAGING C ON
        C.PROTEIN_UID_KEY = B.PROTEIN_UID_KEY
      GROUP BY
        B.ACCESSION_NUMBER,
        B.PROTEIN_UID_KEY,
        B.LOCUS;

CACHE TABLE GENOME_PROTEIN;

SELECT
  COUNT(1) AS NUM_ROWS,
  COUNT(DISTINCT ACCESSION_NUMBER) AS NUM_DISTINCT_GENOMES,
  COUNT(DISTINCT PROTEIN_UID_KEY) AS NUM_DISTINCT_PROTEINS
  FROM
    GENOME_PROTEIN;

SELECT *
  FROM
    GENOME_PROTEIN
    ORDER BY 1, 3
    LIMIT 10;

DROP TABLE GENOME_PROTEIN_STAGING;
