CACHE TABLE GENOME_PROTEIN;

CACHE TABLE PROTEIN_DETAILS_STAGING;

DROP TABLE IF EXISTS PROTEIN_DETAILS;

CREATE TABLE PROTEIN_DETAILS
  USING PARQUET
  AS
  SELECT
    A.PROTEIN_UID_KEY,
    A.PROTEIN_FULLNAME
    FROM
      PROTEIN_DETAILS_STAGING A
      INNER JOIN GENOME_PROTEIN B ON
        B.PROTEIN_UID_KEY = A.PROTEIN_UID_KEY
      GROUP BY
        A.PROTEIN_UID_KEY,
        A.PROTEIN_FULLNAME;

CACHE TABLE PROTEIN_DETAILS;

SELECT
  COUNT(1) AS NUM_ROWS,
  COUNT(DISTINCT PROTEIN_UID_KEY) AS NUM_DISTINCT_PROTEINS,
  COUNT(DISTINCT PROTEIN_FULLNAME) AS NUM_DISTINCT_NAMES
  FROM
    PROTEIN_DETAILS;

SELECT *
  FROM
    PROTEIN_DETAILS
    ORDER BY 1
    LIMIT 10;

DROP TABLE PROTEIN_DETAILS_STAGING;
