CACHE TABLE PROTEIN_VIRULENCE_STAGING;

DROP TABLE IF EXISTS PROTEIN_VIRULENCE;

CREATE TABLE PROTEIN_VIRULENCE
  USING PARQUET
  AS
  SELECT
    PROTEIN_UID_KEY,
    SHORT_NAME,
    FULL_NAME,
    VIRULENCE_FACTOR,
    LOWER(GENUS_NAME) AS GENUS_NAME,
    SPECIES_NAME,
    STRAIN
    FROM
      PROTEIN_VIRULENCE_STAGING;

CACHE TABLE PROTEIN_VIRULENCE;

SELECT
  COUNT(1) AS NUM_ROWS,
  COUNT(DISTINCT PROTEIN_UID_KEY) AS NUM_DISTINCT_PROTEINS
  FROM
    PROTEIN_VIRULENCE;

SELECT *
  FROM
    PROTEIN_VIRULENCE
    ORDER BY 1
    LIMIT 10;

DROP TABLE PROTEIN_VIRULENCE_STAGING;
