@sql/settings.sql;

DROP TABLE IF EXISTS KPS_GENOME_TABLE_STAGING;

CREATE TABLE KPS_GENOME_TABLE_STAGING (
  ACCESSION_NUMBER STRING,
  SCIENTIFIC_NAME STRING,
  TAX_ID INT,
  NCBI_ID INT,
  IS_HAISEQ STRING,
  SUBMISSION_DATE STRING,
  COLLECTION_DATE STRING)
  USING csv
    OPTIONS (
      header true,
      path '${outputs_dir}/klebsiella_pneumoniae_strains.csv');

CACHE TABLE KPS_GENOME_TABLE_STAGING;

DROP TABLE IF EXISTS KPS_GENOME_TABLE;

CREATE TABLE KPS_GENOME_TABLE
  USING PARQUET
  AS
  SELECT *
    FROM
      KPS_GENOME_TABLE_STAGING;

CACHE TABLE KPS_GENOME_TABLE;

SELECT
  COUNT(1) AS NUM_ROWS,
  COUNT(DISTINCT ACCESSION_NUMBER) AS NUM_DISTINCT_GENOMES,
  COUNT(DISTINCT SCIENTIFIC_NAME) AS NUM_DISTINCT_NAMES,
  COUNT(DISTINCT TAX_ID) AS NUM_DISTINCT_TAX_IDS
  FROM
    KPS_GENOME_TABLE;

SELECT
  COUNT(1) AS NUM_HAISEQ
  FROM
    KPS_GENOME_TABLE
    WHERE
      IS_HAISEQ = 'Y';

SELECT *
  FROM
    KPS_GENOME_TABLE
    ORDER BY 1
    LIMIT 10;

DROP TABLE KPS_GENOME_TABLE_STAGING;
