@sql/settings.sql;

DROP TABLE IF EXISTS GENE_VIRULENCE_STAGING;

CREATE TABLE GENE_VIRULENCE_STAGING (
  GENE_UID_KEY STRING,
  SHORT_NAME STRING,
  FULL_NAME STRING,
  VIRULENCE_FACTOR STRING,
  GENUS_NAME STRING,
  SPECIES_NAME STRING,
  STRAIN STRING)
    USING csv
    OPTIONS (
      header false,
      path '${data_dir}/gene_virulence.csv');

CACHE TABLE GENE_VIRULENCE_STAGING;

SELECT
  COUNT(1) AS NUM_ROWS,
  COUNT(DISTINCT GENE_UID_KEY) AS NUM_DISTINCT_GENES
  FROM
    GENE_VIRULENCE_STAGING;
