@sql/settings.sql;

DROP TABLE IF EXISTS GENOME_TABLE_STAGING;

CREATE TABLE GENOME_TABLE_STAGING (
  GENUS_NAME STRING,
  ACCESSION_NUMBER STRING)
    USING csv
    OPTIONS (
      header false,
      path '${data_dir}/genome_table.csv');

CACHE TABLE GENOME_TABLE_STAGING;

SELECT
  COUNT(1) AS NUM_ROWS,
  COUNT(DISTINCT GENUS_NAME) AS NUM_DISTINCT_GENERA,
  COUNT(DISTINCT ACCESSION_NUMBER) AS NUM_DISTINCT_GENOMES
  FROM
    GENOME_TABLE_STAGING;
