@sql/settings.sql;

DROP TABLE IF EXISTS IPR_STAGING;

CREATE TABLE IPR_STAGING (
  IPR_ACCESSION STRING,
  NAME STRING,
  DESCRIPTION STRING,
  TYPE STRING)
    USING csv
    OPTIONS (
      header false,
      path '${data_dir}/ipr.csv');

CACHE TABLE IPR_STAGING;

SELECT
  COUNT(1) AS NUM_ROWS,
  COUNT(DISTINCT IPR_ACCESSION) AS NUM_DISTINCT_IPRS,
  COUNT(DISTINCT TYPE) AS NUM_DISTINCT_TYPES
  FROM
    IPR_STAGING;
