@sql/settings.sql;

DROP TABLE IF EXISTS PROTEIN_DETAILS_STAGING;

CREATE TABLE PROTEIN_DETAILS_STAGING (
  PROTEIN_UID_KEY STRING,
  PROTEIN_FULLNAME STRING)
    USING csv
    OPTIONS (
      header false,
      path '${data_dir}/protein_details.csv');

CACHE TABLE PROTEIN_DETAILS_STAGING;

SELECT
  COUNT(1) AS NUM_ROWS,
  COUNT(DISTINCT PROTEIN_UID_KEY) AS NUM_DISTINCT_PROTEINS,
  COUNT(DISTINCT PROTEIN_FULLNAME) AS NUM_DISTINCT_NAMES
  FROM
    PROTEIN_DETAILS_STAGING;
