@sql/settings.sql;

DROP TABLE IF EXISTS PROTEIN_VIRULENCE_STAGING;

CREATE TABLE PROTEIN_VIRULENCE_STAGING (
  PROTEIN_UID_KEY STRING,
  SHORT_NAME STRING,
  FULL_NAME STRING,
  VIRULENCE_FACTOR STRING,
  GENUS_NAME STRING,
  SPECIES_NAME STRING,
  STRAIN STRING)
    USING csv
    OPTIONS (
      header false,
      path '${data_dir}/protein_virulence.csv');

CACHE TABLE PROTEIN_VIRULENCE_STAGING;

SELECT
  COUNT(1) AS NUM_ROWS,
  COUNT(DISTINCT PROTEIN_UID_KEY) AS NUM_DISTINCT_PROTEINS
  FROM
    PROTEIN_VIRULENCE_STAGING;
