CACHE TABLE GENOME_PIVOT_NEIGHBOR_PROTEIN_DOMAIN;

DROP TABLE IF EXISTS GENOME_PIVOT_NEIGHBOR_DOMAIN_COUNT;

CREATE TABLE GENOME_PIVOT_NEIGHBOR_DOMAIN_COUNT
  USING PARQUET
  AS
  SELECT
    ACCESSION_NUMBER,
    PIVOT_DOMAIN_ARCHITECTURE_UID_KEY,
    NEIGHBOR_DOMAIN_ARCHITECTURE_UID_KEY,
    NEIGHBOR_TYPE,
    COUNT(NEIGHBOR_DOMAIN_ARCHITECTURE_UID_KEY) AS COUNT
    FROM
      GENOME_PIVOT_NEIGHBOR_PROTEIN_DOMAIN
      GROUP BY
        ACCESSION_NUMBER,
        PIVOT_DOMAIN_ARCHITECTURE_UID_KEY,
        NEIGHBOR_DOMAIN_ARCHITECTURE_UID_KEY,
        NEIGHBOR_TYPE;

CACHE TABLE GENOME_PIVOT_NEIGHBOR_DOMAIN_COUNT;

SELECT
  COUNT(1) AS NUM_ROWS,
  COUNT(DISTINCT ACCESSION_NUMBER) AS NUM_DISTINCT_GENOMES,
  COUNT(DISTINCT PIVOT_DOMAIN_ARCHITECTURE_UID_KEY) AS NUM_DISTINCT_PIVOT_DAS,
  COUNT(DISTINCT NEIGHBOR_DOMAIN_ARCHITECTURE_UID_KEY) AS NUM_DISTINCT_NEIGHBOR_DAS
  FROM
    GENOME_PIVOT_NEIGHBOR_DOMAIN_COUNT;

SELECT *
  FROM
    GENOME_PIVOT_NEIGHBOR_DOMAIN_COUNT
    ORDER BY 1, 5 DESC
    LIMIT 10;
