@sql/settings.sql;

CACHE TABLE GENUS_PIVOT_NEIGHBOR_DOMAIN_COUNT;

DROP TABLE IF EXISTS GENUS_MINIMUM_CUTOFF_THRESHOLD;

CREATE TABLE GENUS_MINIMUM_CUTOFF_THRESHOLD
  USING PARQUET
  AS
  SELECT
    GENUS_NAME,
    MCT(COLLECT_LIST(COUNT), GENUS_NAME, '${plots_dir}/mct') AS THRESHOLD
    FROM
      GENUS_PIVOT_NEIGHBOR_DOMAIN_COUNT
      WHERE
        NEIGHBOR_DOMAIN_ARCHITECTURE_UID_KEY IS NOT NULL AND
        NEIGHBOR_TYPE = 'PD'
      GROUP BY
        GENUS_NAME;

SELECT
  COUNT(1) AS NUM_ROWS,
  COUNT(DISTINCT GENUS_NAME) AS NUM_DISTINCT_GENERA
  FROM
    GENUS_MINIMUM_CUTOFF_THRESHOLD;

SELECT *
  FROM
    GENUS_MINIMUM_CUTOFF_THRESHOLD
    ORDER BY 1
    LIMIT 10;
