CACHE TABLE GENUS_PIVOT_NEIGHBOR_DOMAIN_COUNT_FINAL;

DROP TABLE IF EXISTS PIVOT_COPIVOT_FREQUENCY;

CREATE TABLE PIVOT_COPIVOT_FREQUENCY
  USING PARQUET
  AS
  SELECT
    PIVOT_DOMAIN_ARCHITECTURE_UID_KEY,
    NEIGHBOR_DOMAIN_ARCHITECTURE_UID_KEY,
    SUM(COUNT) AS COUNT
    FROM
      GENUS_PIVOT_NEIGHBOR_DOMAIN_COUNT_FINAL
      WHERE
        NEIGHBOR_TYPE = 'C'
      GROUP BY
        PIVOT_DOMAIN_ARCHITECTURE_UID_KEY,
        NEIGHBOR_DOMAIN_ARCHITECTURE_UID_KEY;

CACHE TABLE PIVOT_COPIVOT_FREQUENCY;

SELECT
  COUNT(1) AS NUM_ROWS,
  COUNT(DISTINCT PIVOT_DOMAIN_ARCHITECTURE_UID_KEY) AS NUM_DISTINCT_PIVOTS,
  COUNT(DISTINCT NEIGHBOR_DOMAIN_ARCHITECTURE_UID_KEY) AS NUM_DISTINCT_COPIVOTS
  FROM
    PIVOT_COPIVOT_FREQUENCY;

SELECT *
  FROM
    PIVOT_COPIVOT_FREQUENCY
    ORDER BY 1, 2
    LIMIT 10;
