CACHE TABLE KLEBSIELLA_LABELED;

CACHE TABLE KLEBSIELLA_LABELED_GENOME_PIVOT_NEIGHBOR_DOMAIN_COUNT_FINAL;

DROP TABLE IF EXISTS KLEBSIELLA_CLASSIFIER_ROW_LABEL;

CREATE TABLE KLEBSIELLA_CLASSIFIER_ROW_LABEL
  USING PARQUET
  AS
  SELECT
    INDEX - 1 AS INDEX,
    LABEL
    FROM
      (SELECT
        ROW_NUMBER() OVER(ORDER BY ACCESSION_NUMBER) AS INDEX,
        ACCESSION_NUMBER AS LABEL
        FROM
          KLEBSIELLA_LABELED_GENOME_PIVOT_NEIGHBOR_DOMAIN_COUNT_FINAL
          GROUP BY
            ACCESSION_NUMBER);

CACHE TABLE KLEBSIELLA_CLASSIFIER_ROW_LABEL;

SELECT
  COUNT(1) AS NUM_ROWS,
  COUNT(DISTINCT INDEX) AS NUM_DISTINCT_INDEXES,
  COUNT(DISTINCT LABEL) AS NUM_DISTINCT_LABELS
  FROM
    KLEBSIELLA_CLASSIFIER_ROW_LABEL;

SELECT *
  FROM
    KLEBSIELLA_CLASSIFIER_ROW_LABEL
    ORDER BY 1
    LIMIT 10;

DROP TABLE IF EXISTS KLEBSIELLA_CLASSIFIER_COL_LABEL;

CREATE TABLE KLEBSIELLA_CLASSIFIER_COL_LABEL
  USING PARQUET
  AS
  SELECT
    INDEX - 1 AS INDEX,
    LABEL
    FROM
      (SELECT
        ROW_NUMBER() OVER(ORDER BY NEIGHBOR_DOMAIN_ARCHITECTURE_UID_KEY) AS INDEX,
        NEIGHBOR_DOMAIN_ARCHITECTURE_UID_KEY AS LABEL
        FROM
          KLEBSIELLA_LABELED_GENOME_PIVOT_NEIGHBOR_DOMAIN_COUNT_FINAL
          GROUP BY
            NEIGHBOR_DOMAIN_ARCHITECTURE_UID_KEY);

CACHE TABLE KLEBSIELLA_CLASSIFIER_COL_LABEL;

SELECT
  COUNT(1) AS NUM_ROWS,
  COUNT(DISTINCT INDEX) AS NUM_DISTINCT_INDEXES,
  COUNT(DISTINCT LABEL) AS NUM_DISTINCT_LABELS
  FROM
    KLEBSIELLA_CLASSIFIER_COL_LABEL;

SELECT *
  FROM
    KLEBSIELLA_CLASSIFIER_COL_LABEL
    ORDER BY 1
    LIMIT 10;

DROP TABLE IF EXISTS KLEBSIELLA_CLASSIFIER_FEATURE;

CREATE TABLE KLEBSIELLA_CLASSIFIER_FEATURE
  USING PARQUET
  AS
  SELECT
    ROW_INDEX,
    LABEL,
    SORT_VECTOR(COLLECT_LIST(COL_INDEX || ':' || COUNT)) AS FEATURES
    FROM
      (SELECT
        A.VIRULENCE_CATEGORY2 AS LABEL,
        C.INDEX AS ROW_INDEX,
        D.INDEX AS COL_INDEX,
        SUM(B.COUNT) AS COUNT
        FROM
          KLEBSIELLA_LABELED A
          INNER JOIN KLEBSIELLA_LABELED_GENOME_PIVOT_NEIGHBOR_DOMAIN_COUNT_FINAL B ON
            B.ACCESSION_NUMBER = A.ACCESSION_NUMBER
          INNER JOIN KLEBSIELLA_CLASSIFIER_ROW_LABEL C ON
            C.LABEL = B.ACCESSION_NUMBER
          INNER JOIN KLEBSIELLA_CLASSIFIER_COL_LABEL D ON
            D.LABEL = B.NEIGHBOR_DOMAIN_ARCHITECTURE_UID_KEY
          GROUP BY
            A.VIRULENCE_CATEGORY2,
            C.INDEX,
            D.INDEX)
      GROUP BY
        ROW_INDEX,
        LABEL;

CACHE TABLE KLEBSIELLA_CLASSIFIER_FEATURE;

SELECT
  COUNT(1) AS NUM_ROWS,
  COUNT(DISTINCT ROW_INDEX) AS NUM_DISTINCT_ROW_INDEXES,
  COUNT(DISTINCT LABEL) AS NUM_DISTINCT_LABELS,
  MIN(SIZE(FEATURES)) AS MIN_FEATURES_SIZE,
  AVG(SIZE(FEATURES)) AS AVG_FEATURES_SIZE,
  MAX(SIZE(FEATURES)) AS MAX_FEATURES_SIZE
  FROM
    KLEBSIELLA_CLASSIFIER_FEATURE;

SELECT *
  FROM
    KLEBSIELLA_CLASSIFIER_FEATURE
    ORDER BY 1
    LIMIT 1;
